/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.GutosHamburguers.view;

/**
 *
 * @author euamo
 */
public class PainelPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PainelPrincipal
     */
    public PainelPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColunaPrincipal = new javax.swing.JPanel();
        Logotipo = new javax.swing.JLabel();
        btPerfil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btCadastro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btPedidos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btSair = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jpaneMain = new javax.swing.JPanel();
        windowSair = new javax.swing.JPanel();
        colunahorizontal4 = new javax.swing.JPanel();
        windowPedidos = new javax.swing.JPanel();
        colunahorizontal2 = new javax.swing.JPanel();
        barraPesquisar = new javax.swing.JTextField();
        botaoPesquisar = new javax.swing.JButton();
        btLanches = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btBebidas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btConfirmarPedidos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        mainPedidos = new javax.swing.JPanel();
        jpaneLanches = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jpaneBebidas = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpaneConfirmarPedido = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        windowPerfil = new javax.swing.JPanel();
        colunahorizontal1 = new javax.swing.JPanel();
        jpanePerfil = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        barraNome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        barraEndereço = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        windowCadastro = new javax.swing.JPanel();
        colunahorizontal3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ColunaPrincipal.setBackground(new java.awt.Color(215, 57, 57));

        Logotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/GutosHamburguers/view/GUT´S.png"))); // NOI18N
        Logotipo.setText("jLabel1");

        btPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btPerfilMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("PERFIL");

        javax.swing.GroupLayout btPerfilLayout = new javax.swing.GroupLayout(btPerfil);
        btPerfil.setLayout(btPerfilLayout);
        btPerfilLayout.setHorizontalGroup(
            btPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btPerfilLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        btPerfilLayout.setVerticalGroup(
            btPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCadastroMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("CADASTRO");

        javax.swing.GroupLayout btCadastroLayout = new javax.swing.GroupLayout(btCadastro);
        btCadastro.setLayout(btCadastroLayout);
        btCadastroLayout.setHorizontalGroup(
            btCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btCadastroLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(74, 74, 74))
        );
        btCadastroLayout.setVerticalGroup(
            btCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btCadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        btPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btPedidosMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("PEDIDOS");

        javax.swing.GroupLayout btPedidosLayout = new javax.swing.GroupLayout(btPedidos);
        btPedidos.setLayout(btPedidosLayout);
        btPedidosLayout.setHorizontalGroup(
            btPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPedidosLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        btPedidosLayout.setVerticalGroup(
            btPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btPedidosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("SAIR");

        javax.swing.GroupLayout btSairLayout = new javax.swing.GroupLayout(btSair);
        btSair.setLayout(btSairLayout);
        btSairLayout.setHorizontalGroup(
            btSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btSairLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel4)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        btSairLayout.setVerticalGroup(
            btSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btSairLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Av Emídio Calixto - Acopiara - CE");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("(88) 99772 1204");

        javax.swing.GroupLayout ColunaPrincipalLayout = new javax.swing.GroupLayout(ColunaPrincipal);
        ColunaPrincipal.setLayout(ColunaPrincipalLayout);
        ColunaPrincipalLayout.setHorizontalGroup(
            ColunaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ColunaPrincipalLayout.createSequentialGroup()
                .addGroup(ColunaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ColunaPrincipalLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(ColunaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ColunaPrincipalLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel16))
                    .addGroup(ColunaPrincipalLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel15)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        ColunaPrincipalLayout.setVerticalGroup(
            ColunaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ColunaPrincipalLayout.createSequentialGroup()
                .addComponent(Logotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(75, 75, 75))
        );

        colunahorizontal4.setBackground(new java.awt.Color(242, 53, 53));

        javax.swing.GroupLayout colunahorizontal4Layout = new javax.swing.GroupLayout(colunahorizontal4);
        colunahorizontal4.setLayout(colunahorizontal4Layout);
        colunahorizontal4Layout.setHorizontalGroup(
            colunahorizontal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        colunahorizontal4Layout.setVerticalGroup(
            colunahorizontal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout windowSairLayout = new javax.swing.GroupLayout(windowSair);
        windowSair.setLayout(windowSairLayout);
        windowSairLayout.setHorizontalGroup(
            windowSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colunahorizontal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        windowSairLayout.setVerticalGroup(
            windowSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowSairLayout.createSequentialGroup()
                .addComponent(colunahorizontal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 543, Short.MAX_VALUE))
        );

        colunahorizontal2.setBackground(new java.awt.Color(242, 53, 53));

        barraPesquisar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        botaoPesquisar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botaoPesquisar.setText("PESQUISAR");

        javax.swing.GroupLayout colunahorizontal2Layout = new javax.swing.GroupLayout(colunahorizontal2);
        colunahorizontal2.setLayout(colunahorizontal2Layout);
        colunahorizontal2Layout.setHorizontalGroup(
            colunahorizontal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colunahorizontal2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barraPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        colunahorizontal2Layout.setVerticalGroup(
            colunahorizontal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colunahorizontal2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(colunahorizontal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barraPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        btLanches.setBackground(new java.awt.Color(217, 95, 95));
        btLanches.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btLanches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLanchesMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("LANCHES");

        javax.swing.GroupLayout btLanchesLayout = new javax.swing.GroupLayout(btLanches);
        btLanches.setLayout(btLanchesLayout);
        btLanchesLayout.setHorizontalGroup(
            btLanchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btLanchesLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        btLanchesLayout.setVerticalGroup(
            btLanchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btLanchesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btBebidas.setBackground(new java.awt.Color(217, 95, 95));
        btBebidas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btBebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBebidasMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("BEBIDAS");

        javax.swing.GroupLayout btBebidasLayout = new javax.swing.GroupLayout(btBebidas);
        btBebidas.setLayout(btBebidasLayout);
        btBebidasLayout.setHorizontalGroup(
            btBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btBebidasLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel6)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        btBebidasLayout.setVerticalGroup(
            btBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btBebidasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        btConfirmarPedidos.setBackground(new java.awt.Color(217, 95, 95));
        btConfirmarPedidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btConfirmarPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConfirmarPedidosMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("CONFIRMAR PEDIDO");

        javax.swing.GroupLayout btConfirmarPedidosLayout = new javax.swing.GroupLayout(btConfirmarPedidos);
        btConfirmarPedidos.setLayout(btConfirmarPedidosLayout);
        btConfirmarPedidosLayout.setHorizontalGroup(
            btConfirmarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btConfirmarPedidosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        btConfirmarPedidosLayout.setVerticalGroup(
            btConfirmarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btConfirmarPedidosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jLabel8.setText("HAMBURGUER");

        javax.swing.GroupLayout jpaneLanchesLayout = new javax.swing.GroupLayout(jpaneLanches);
        jpaneLanches.setLayout(jpaneLanchesLayout);
        jpaneLanchesLayout.setHorizontalGroup(
            jpaneLanchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneLanchesLayout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel8)
                .addContainerGap(379, Short.MAX_VALUE))
        );
        jpaneLanchesLayout.setVerticalGroup(
            jpaneLanchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneLanchesLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel8)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jLabel9.setText("coca");

        javax.swing.GroupLayout jpaneBebidasLayout = new javax.swing.GroupLayout(jpaneBebidas);
        jpaneBebidas.setLayout(jpaneBebidasLayout);
        jpaneBebidasLayout.setHorizontalGroup(
            jpaneBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneBebidasLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(445, Short.MAX_VALUE))
        );
        jpaneBebidasLayout.setVerticalGroup(
            jpaneBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneBebidasLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel9)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jLabel10.setText("confirmar");

        jLabel11.setText("cancelar");

        javax.swing.GroupLayout jpaneConfirmarPedidoLayout = new javax.swing.GroupLayout(jpaneConfirmarPedido);
        jpaneConfirmarPedido.setLayout(jpaneConfirmarPedidoLayout);
        jpaneConfirmarPedidoLayout.setHorizontalGroup(
            jpaneConfirmarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneConfirmarPedidoLayout.createSequentialGroup()
                .addGroup(jpaneConfirmarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaneConfirmarPedidoLayout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpaneConfirmarPedidoLayout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        jpaneConfirmarPedidoLayout.setVerticalGroup(
            jpaneConfirmarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneConfirmarPedidoLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel10)
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPedidosLayout = new javax.swing.GroupLayout(mainPedidos);
        mainPedidos.setLayout(mainPedidosLayout);
        mainPedidosLayout.setHorizontalGroup(
            mainPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpaneLanches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mainPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPedidosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpaneBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(mainPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPedidosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpaneConfirmarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        mainPedidosLayout.setVerticalGroup(
            mainPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpaneLanches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(mainPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPedidosLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jpaneBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
            .addGroup(mainPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPedidosLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jpaneConfirmarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
        );

        javax.swing.GroupLayout windowPedidosLayout = new javax.swing.GroupLayout(windowPedidos);
        windowPedidos.setLayout(windowPedidosLayout);
        windowPedidosLayout.setHorizontalGroup(
            windowPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colunahorizontal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(windowPedidosLayout.createSequentialGroup()
                .addComponent(btLanches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btConfirmarPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(mainPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        windowPedidosLayout.setVerticalGroup(
            windowPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowPedidosLayout.createSequentialGroup()
                .addComponent(colunahorizontal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(windowPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btLanches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConfirmarPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        colunahorizontal1.setBackground(new java.awt.Color(242, 53, 53));

        javax.swing.GroupLayout colunahorizontal1Layout = new javax.swing.GroupLayout(colunahorizontal1);
        colunahorizontal1.setLayout(colunahorizontal1Layout);
        colunahorizontal1Layout.setHorizontalGroup(
            colunahorizontal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        colunahorizontal1Layout.setVerticalGroup(
            colunahorizontal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jpanePerfil.setBackground(new java.awt.Color(253, 196, 163));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("NOME:");

        barraNome.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("ENDEREÇO:");

        barraEndereço.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("NÚMERO:");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(217, 95, 95));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel18.setText("PERFIL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpanePerfilLayout = new javax.swing.GroupLayout(jpanePerfil);
        jpanePerfil.setLayout(jpanePerfilLayout);
        jpanePerfilLayout.setHorizontalGroup(
            jpanePerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanePerfilLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpanePerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanePerfilLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barraEndereço))
                    .addGroup(jpanePerfilLayout.createSequentialGroup()
                        .addGroup(jpanePerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanePerfilLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barraNome, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanePerfilLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jpanePerfilLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanePerfilLayout.setVerticalGroup(
            jpanePerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanePerfilLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpanePerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanePerfilLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jpanePerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(barraNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpanePerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(barraEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpanePerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpanePerfilLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout windowPerfilLayout = new javax.swing.GroupLayout(windowPerfil);
        windowPerfil.setLayout(windowPerfilLayout);
        windowPerfilLayout.setHorizontalGroup(
            windowPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colunahorizontal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(windowPerfilLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jpanePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        windowPerfilLayout.setVerticalGroup(
            windowPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowPerfilLayout.createSequentialGroup()
                .addComponent(colunahorizontal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpanePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        colunahorizontal3.setBackground(new java.awt.Color(242, 53, 53));

        javax.swing.GroupLayout colunahorizontal3Layout = new javax.swing.GroupLayout(colunahorizontal3);
        colunahorizontal3.setLayout(colunahorizontal3Layout);
        colunahorizontal3Layout.setHorizontalGroup(
            colunahorizontal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        colunahorizontal3Layout.setVerticalGroup(
            colunahorizontal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout windowCadastroLayout = new javax.swing.GroupLayout(windowCadastro);
        windowCadastro.setLayout(windowCadastroLayout);
        windowCadastroLayout.setHorizontalGroup(
            windowCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colunahorizontal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        windowCadastroLayout.setVerticalGroup(
            windowCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowCadastroLayout.createSequentialGroup()
                .addComponent(colunahorizontal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 509, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpaneMainLayout = new javax.swing.GroupLayout(jpaneMain);
        jpaneMain.setLayout(jpaneMainLayout);
        jpaneMainLayout.setHorizontalGroup(
            jpaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(windowCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(windowPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(windowSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpaneMainLayout.setVerticalGroup(
            jpaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(windowCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(windowPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(windowSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ColunaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColunaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPerfilMouseClicked
        // TODO add your handling code here:
        
        windowPerfil.setVisible(true);
        windowCadastro.setVisible(false);
        windowPedidos.setVisible(false);
        windowSair.setVisible(false);
        botaoPesquisar.setVisible(false);
        barraPesquisar.setVisible(false);
        
    }//GEN-LAST:event_btPerfilMouseClicked

    private void btCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastroMouseClicked
        // TODO add your handling code here:
        
        windowPerfil.setVisible(false);
        windowCadastro.setVisible(true);
        windowPedidos.setVisible(false);
        windowSair.setVisible(false);
        botaoPesquisar.setVisible(false);
        barraPesquisar.setVisible(false);
        
    }//GEN-LAST:event_btCadastroMouseClicked

    private void btPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPedidosMouseClicked
        // TODO add your handling code here:
        
        windowPerfil.setVisible(false);
        windowCadastro.setVisible(false);
        windowPedidos.setVisible(true);
        windowSair.setVisible(false);
        botaoPesquisar.setVisible(true);
        barraPesquisar.setVisible(true);
    }//GEN-LAST:event_btPedidosMouseClicked

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked
        // TODO add your handling code here:
        
        windowPerfil.setVisible(false);
        windowCadastro.setVisible(false);
        windowPedidos.setVisible(false);
        windowSair.setVisible(true);
        botaoPesquisar.setVisible(false);
        barraPesquisar.setVisible(false);
    }//GEN-LAST:event_btSairMouseClicked

    private void btLanchesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLanchesMouseClicked
        // TODO add your handling code here:
        
        jpaneLanches.setVisible(true);
        jpaneBebidas.setVisible(false);
        jpaneConfirmarPedido.setVisible(false);
    }//GEN-LAST:event_btLanchesMouseClicked

    private void btBebidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBebidasMouseClicked
        // TODO add your handling code here:
        
        jpaneLanches.setVisible(false);
        jpaneBebidas.setVisible(true);
        jpaneConfirmarPedido.setVisible(false);
    }//GEN-LAST:event_btBebidasMouseClicked

    private void btConfirmarPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConfirmarPedidosMouseClicked
        // TODO add your handling code here:
        
        jpaneLanches.setVisible(false);
        jpaneBebidas.setVisible(false);
        jpaneConfirmarPedido.setVisible(true);
    }//GEN-LAST:event_btConfirmarPedidosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ColunaPrincipal;
    private javax.swing.JLabel Logotipo;
    private javax.swing.JTextField barraEndereço;
    private javax.swing.JTextField barraNome;
    private javax.swing.JTextField barraPesquisar;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JPanel btBebidas;
    private javax.swing.JPanel btCadastro;
    private javax.swing.JPanel btConfirmarPedidos;
    private javax.swing.JPanel btLanches;
    private javax.swing.JPanel btPedidos;
    private javax.swing.JPanel btPerfil;
    private javax.swing.JPanel btSair;
    private javax.swing.JPanel colunahorizontal1;
    private javax.swing.JPanel colunahorizontal2;
    private javax.swing.JPanel colunahorizontal3;
    private javax.swing.JPanel colunahorizontal4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpaneBebidas;
    private javax.swing.JPanel jpaneConfirmarPedido;
    private javax.swing.JPanel jpaneLanches;
    private javax.swing.JPanel jpaneMain;
    private javax.swing.JPanel jpanePerfil;
    private javax.swing.JPanel mainPedidos;
    private javax.swing.JPanel windowCadastro;
    private javax.swing.JPanel windowPedidos;
    private javax.swing.JPanel windowPerfil;
    private javax.swing.JPanel windowSair;
    // End of variables declaration//GEN-END:variables
}
